# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# http://docs.travis-ci.com

after_success:
  - $(npm bin)/update-branch --commands "npm install && npm run build"
                             --commit-message "Hey GitHub, this content is for you! [skip ci]"
                             --directory "build"
                             --distribution-branch "gh-pages"
                             --source-branch "master"

env:
  global:
    - secure: "CguKtZSKYsXk2etsFE7FMejylxCWNycuozhKWdAkZF4Dc0LbRFEXSHHB6vaEaa7BO0HbyYTkCx4aWiztVDdPeSAERmeCITteKKs6pew1uDVGLOlOlOP/wpQgrL9mOl74yPyKSV9fHMLakeOKQlY/2fVeQ0m1GGerGBuslLSSygE="

git:
  depth: 10

language: node_js

node_js:
  - "4"
